list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/packages")

set(THIRD_PARTY "third-party" CACHE STRING "3rdparty folder for project dependencies. [Don't change this variable.]")
option(PROJECT_ENABLE_TEMPLATE_DEPENDENCIES "Enable optional template dependency discovery (Boost/OpenSSL/etc.)." OFF)

find_package(Git)
if(Git_FOUND)
  message("Git found: ${GIT_EXECUTABLE}")
endif()

find_package(Curl       REQUIRED)
find_package(JSon       REQUIRED)

if(PROJECT_ENABLE_TEMPLATE_DEPENDENCIES)
  find_package(Boost      QUIET)
  find_package(OpenSSL    QUIET)
  find_package(Cryptopp   QUIET)
  find_package(OpenCV     QUIET)
  find_package(OpenMesh   QUIET)
  find_package(GTest      QUIET)
  find_package(DocTest    QUIET)
  find_package(Catch2     QUIET)
  find_package(Fmt        QUIET)
  find_package(Jwt        QUIET)
  find_package(Ctre       QUIET)
  find_package(Zlib       QUIET)
  find_package(Eigen      QUIET)
endif()

if (USE_CUSTOM_ENGINE)
  find_package(${ENGINE_CODE_NAME}  REQUIRED)
endif()
